### ISSUE TITLE
OmnomIRC Regexes

### ISSUE THREAD

**Issue by Sorunome** [Eeems/EeeZorBot#17]
1st - support usernames with spaces
2nd - support wildcard characters inside of () so that stuff like (S) is working. The "official" ones actually use [a-zA-Z]+ for that
https://github.com/Sorunome/OmnomIRC2/blob/master/omnombindings_hexchat.py#L42-L87

**Comment by Eeems** [comment]
7b14f48 adds support for nicks with spaces in normal messages. No idea how to handle them in actions yet.
I'll close this ticket. Open a new one if OIRC implements a way to allow detection of names with spaces on actions.
