### ISSUE TITLE
[log] Nick wrong

### ISSUE THREAD

**Issue by Sorunome** [Eeems/EeeZorBot#9]
When using the &gt; char nicks get wrong
&lt;Derpy> &lt;b>test&lt;/b>
gives
{"type":"privmsg","user":"Derpy> &lt;b","msg":"test&lt;/b>","date":1389304990792}

**Comment by Eeems** [comment]
Shouldn't be a problem in the re-org branch. Will close when that merges into master.

**Comment by Eeems** [comment]
Going to start closing issues that are fixed in re-org
